geminiconfig:
  googleproject: "acn-genlite"
  googleservicelocation: "us-central1"
  modelname: "gemini-pro"
  max_output_tokens: "6144"
  json_key: "acn-genlite.json"
  temperature: "0"
  top_p: "0.5"
bisonconfig:
  googleproject: "acn-genlite"
  googleservicelocation: "us-central1"
  modelname: "text-bison-32k"
  max_output_tokens: "8192"
  json_key: "acn-genlite.json"
  temperature: "0.1"
  top_p: "0.5"
azuregpt35config:
  api_key: "74a1ae11ad0e41d8a49d20f0b6f07a1d"
  api_key_vault_key: "CompletionApiKey"
  azure_endpoint: "https://src-sbx-openai.openai.azure.com/"
  api_version: "2023-09-15-preview"
  azure_deployment: "gpt-35-turbo-16k"
  modelname: "gpt-35-turbo-16k"
azuregpt4config:
 api_key: "74a1ae11ad0e41d8a49d20f0b6f07a1d"
 api_key_vault_key: "CompletionApiKey"
 azure_endpoint: "https://src-sbx-openai.openai.azure.com/"
 api_version: "2024-02-01"
 azure_deployment: "gpt-4"
 modelname: "gpt-4"
awstitan:
  service_name: "bedrock-runtime"
  region_name: "us-west-2"
  aws_access_key_id: "azurevault"
  aws_access_key_id_vault_key: "AKIAZAZL6P6HZP2Q4MMR"
  aws_secret_access_key: "azurevault"
  aws_secret_access_key_vault_key: "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"
  bedrock_assume_role: "arn:aws:iam::620178079631:role/AmazonSageMaker-ExecutionRole"
  modelId: "amazon.titan-text-express-v1"
  maxTokenCount: "7999"
  temperature: "0"
  topP: "0.5"
neo4j:
  NEO4J-URL: "neo4j+s://a81a5cd7.databases.neo4j.io:7687"
  NEO4J-USER: "neo4j"
  NEO4J-PASSWORD: ""